/**
 * src/engine/ai/nn/onnxInference.ts
 *
 * ONNX Runtime Web inference for the browser. This is the ORT-backed
 * counterpart to `predictActionSync` in `./model.ts`. The public API is
 * fully async — the sync `AIEngine.planTurn` contract cannot be satisfied
 * from ORT-Web (no `runSync`), so callers must use `planTurnAsync` /
 * `asyncTurnRunner`.
 *
 * Bundled artefacts:
 *   /onnx/supreme_champion_32.onnx    (~1.5 MB fp32)
 *   /onnx/supreme_champion_64.onnx    (~3.0 MB fp32)
 *
 * Regenerated by `npm run onnx:convert` and parity-checked by
 * `npm run onnx:verify` — see doc/CHECKPOINT_CONVERSION.md.
 */

import * as ort from 'onnxruntime-web';
import type { GameState, Side } from '../../types';
import type { MCTSCandidateAction } from '../mcts/mcts';
import { encodeStateTensor } from './encoders';
import { encodeCandidateIndex } from './actionCodec';

export type ModelSize = '32' | '64';

/**
 * Where the `.wasm` binaries served by onnxruntime-web live. Vite's
 * static-copy plugin drops the ORT distribution into `/ort/` at build
 * time; see `vite.config.ts`. Overridable for tests / alternative hosts.
 */
export function configureONNXRuntime(opts: { wasmPaths?: string } = {}): void {
  if (opts.wasmPaths) {
    (ort.env.wasm as { wasmPaths?: string }).wasmPaths = opts.wasmPaths;
  } else if (!(ort.env.wasm as { wasmPaths?: string }).wasmPaths) {
    (ort.env.wasm as { wasmPaths?: string }).wasmPaths = '/ort/';
  }
}

const MODEL_URLS: Record<ModelSize, string> = {
  '32': '/onnx/supreme_champion_32.onnx',
  '64': '/onnx/supreme_champion_64.onnx',
};

interface SessionEntry {
  session: ort.InferenceSession;
  providerName: string;
}

const sessions: Partial<Record<ModelSize, SessionEntry>> = {};
const loading: Partial<Record<ModelSize, Promise<SessionEntry>>> = {};

/**
 * Get or create the ORT session for the given model size. Concurrent
 * callers coalesce onto a single in-flight load.
 */
export async function getSession(size: ModelSize): Promise<SessionEntry> {
  const cached = sessions[size];
  if (cached) return cached;
  const inflight = loading[size];
  if (inflight) return inflight;

  configureONNXRuntime();

  const promise = ort.InferenceSession.create(MODEL_URLS[size], {
    executionProviders: ['webgpu', 'wasm'],
    graphOptimizationLevel: 'all',
  }).then(session => {
    // ORT does not expose the selected provider on the session object in
    // a stable way, but the request order gives us a best-effort label.
    // Real telemetry happens on the first successful run() call.
    const entry: SessionEntry = { session, providerName: 'unknown' };
    sessions[size] = entry;
    delete loading[size];
    return entry;
  }).catch(err => {
    delete loading[size];
    throw err;
  });

  loading[size] = promise;
  return promise;
}

/**
 * Warm-start: fetch + compile the model and run a single dummy forward
 * pass, so the first real AI turn doesn't eat the entire warm-up cost.
 * Call this from App.tsx on mount.
 */
export async function warmUpONNX(size: ModelSize): Promise<void> {
  const { session } = await getSession(size);
  const channels = size === '32' ? 32 : 64;
  const dummy = new Float32Array(11 * 11 * channels);
  const inputName = session.inputNames[0];
  const inputTensor = new ort.Tensor('float32', dummy, [1, 11, 11, channels]);
  await session.run({ [inputName]: inputTensor });
}

export interface OnnxPredictionResult {
  bestAction: MCTSCandidateAction;
  value: number;
  policyScores: Float32Array;
}

/**
 * Async equivalent of `predictActionSync` from ./model.ts, backed by
 * ONNX Runtime Web instead of TFJS. Identical input/output contract so
 * `NNEngine.planTurnAsync` can swap between the two behind a config flag.
 */
export async function predictActionAsync(
  size: ModelSize,
  state: GameState,
  candidates: MCTSCandidateAction[],
  actingSide: Side = 'AI',
): Promise<OnnxPredictionResult> {
  if (candidates.length === 0) {
    return { bestAction: { moves: [] }, value: 0, policyScores: new Float32Array(64) };
  }

  const { session } = await getSession(size);
  const channels = size === '32' ? 32 : 64;
  const inputData = encodeStateTensor(state, actingSide, channels);
  const inputName = session.inputNames[0];
  const inputTensor = new ort.Tensor('float32', inputData, [1, 11, 11, channels]);

  const outputs = await session.run({ [inputName]: inputTensor });
  const policyScores = outputs['policy_head']?.data as Float32Array;
  const valueData = outputs['value_head']?.data as Float32Array;
  const value = valueData?.[0] ?? 0;

  let bestAction = candidates[0];
  let bestScore = -Infinity;
  for (const cand of candidates) {
    const idx = encodeCandidateIndex(cand, state, actingSide);
    const score = policyScores?.[idx] ?? 0;
    if (score > bestScore) {
      bestScore = score;
      bestAction = cand;
    }
  }

  return { bestAction, value, policyScores: policyScores || new Float32Array(64) };
}
